pro/app/urls.py
from django.contrib import admin
from django.urls import path
from app import views
app_name='app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.user,name="form"),
    path('show/',views.show,name='show'),
    # path('admin/', admin.site.urls,name='adminpage')

]

pro/pro/urls.py
#from django.contrib import admin
from django.urls import path,include
from app import views
urlpatterns = [
    #path('admin/', admin.site.urls),
    path('',include('app.urls'))
]

pro/app/models.py
from django.db import models
from django.core import validators 
class User(models.Model):
	name=models.CharField(max_length=50)
	mobile=models.IntegerField()
	address=models.CharField(max_length=50)
	email=models.EmailField(unique=True)
	cemail=models.EmailField(unique=True)
	def clean(self):
		all_clean_data=super().clean()
		email=all_clean_data['email']
		cemail=all_clean_data['cemail']
		if(email!=cemail):
			raise forms.ValidationError('make sure email match')

pro/app/forms.py
from django import forms
from app.models import User

class NewUserForm(forms.ModelForm):
	class Meta:
		model=User
		fields='__all__'

pro/app/views.py
from django.shortcuts import render
from app.models import User
from app.forms import NewUserForm
from django.http import HttpResponse,HttpResponseRedirect
def index(request):
	return HttpResponse("your data has been saved")
def user(request):
	form=NewUserForm()
	if(request.method=="POST"):
		form =NewUserForm(request.POST)
		if(form.is_valid()):
			form.save(commit=True)
			return index(request)
		else:
			print("something went wrong")
	return render(request,'app/abc.html',{'form':form})
def show(request):
	obj=User.objects.order_by('name')
	hello={'obj':obj}
	return render (request,'app/show.html',context=hello)					

pro/app/templates/abc.html
<!DOCTYPE html>
<html>
<head>
	<title>Registration</title>
</head>
<body>
	
	<div class ="container">
	<form method="POST">
	{{form.as_p}}
	{% csrf_token%}
	<input type ="SUBMIT"  class="btn btn-primary" value="submit">
	<a href="{% url 'app:show' %}">click here to showdatabase!</a>
	<a href="{% static 'abc.jpg'%"}></a>
	</form>	
   </div>
   <div class ="container">
		{% block body_block %}
		{% endblock%}
	</div>	
</body>
</html>

pro/app/templates/hello.html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
{%if obj %}
<table border="1">
	<tr>
		<th>name</th>
		<th>mobile</th>
	</tr>
	<tr>
	{%for abc in obj%}
	<td>{{abc.name}}</td>
	<td>{{abc.mobile}}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>no data found</p>
{% endif %}
</body>
</html>

pro/app/templates/show.html
<html>
<head>
</head>
<body>
{%if obj %}
<table border="1">
	<tr>
		<th>name</th>
		<th>mobile</th>
		<th>email</th>
	</tr>
	<tr>
	{%for abc in obj%}
	<td>{{abc.name}}</td>
	<td>{{abc.mobile}}</td>
	<td>{{abc.email}}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>no data found</p>
{% endif %}
</body>
</html>

pro/templates/app/abc.html
{%load staticfiles %}
<html>
<head>
	<title>Registration</title>
</head>
<body>
	<div class ="container">
	<form method="POST">
	{{form.as_p}}
	{% csrf_token%}
	<input type ="SUBMIT"  class="btn btn-primary" value="submit">
	<li><a href= "{% url 'app:show' %}">click here to showdatabase!</a></li>
	<img src="{% static 'img.jpg'%}">
	</form>	
   </div>
</body>
</html>

pro/templates/app/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
  <a href=="{% urls 'index'}">click</a>
</body>
</html>

pro/templates/app/show.html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
{%if obj %}
<table border="1">
	<tr>
		<th>name</th>
		<th>mobile</th>
		<th>email</th>
	</tr>
	<tr>
	{%for abc in obj%}
	<td>{{abc.name}}</td>
	<td>{{abc.mobile}}</td>
	<td>{{abc.email}}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>no data found</p>
{% endif %}
</body>
</html>